# Copyright (c) 1998,1999,2001,2002,2003 Kevin Cameron
# Distributed under the GNU Lesser General Public License
# RCS ID: $Id: libv2kprl.pm,v 1.2 2003/01/14 02:26:22 dkc Exp $
 


# This file was automatically generated by SWIG
package libv2kprl;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package libv2kprl;
bootstrap libv2kprl;
var_libv2kprl_init();
package libv2kprl;
@EXPORT = qw( );
1;
